version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_local
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mysql-volume:
  redis-volume: